# https://docs.github.com/actions

name: Docker Hub

on:
  workflow_dispatch:

permissions: {}

jobs:
  stackbrew:
    name: Stackbrew
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          ref: dist

      - name: Download bashbrew
        run: |
          wget https://doi-janky.infosiftr.net/job/bashbrew/job/master/lastSuccessfulBuild/artifact/bashbrew-amd64
          mkdir -p "$HOME/.local/bin"
          mv bashbrew-amd64 "$HOME/.local/bin/bashbrew"
          chmod +x "$HOME/.local/bin/bashbrew"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          bashbrew --version

      - name: Generate stackbrew
        run: bash ./bin/generate-stackbrew-library.sh > yourls

      - uses: actions/upload-artifact@v7
        with:
          name: stackbrew
          path: yourls

  submit:
    name: Submit
    runs-on: ubuntu-latest
    needs:
      - stackbrew
    steps:
      - uses: actions/checkout@v7
        with:
          repository: docker-library/official-images

      - uses: actions/download-artifact@v8
        with:
          name: stackbrew
          path: library

      - name: Generate token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          repositories: docker-library-official-images
          permission-workflows: write
          permission-contents: write

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        id: create-pull-request
        continue-on-error: true
        with:
          token: ${{ steps.app-token.outputs.token }}
          push-to-fork: ${{ github.repository_owner }}/docker-library-official-images
          commit-message: |
            Update YOURLS

            Automated changes from https://github.com/${{ github.repository }}.
            Generated by [GitHub Actions run #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          committer: ${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>
          title: Update YOURLS
          delete-branch: true

      - name: Getting pull request link
        if: ${{ steps.create-pull-request.outcome == 'failure' }}
        run: echo "https://github.com/docker-library/official-images/compare/master...${{ github.repository_owner }}:docker-library-official-images:${{ steps.create-pull-request.outputs.pull-request-branch }}"
